version: '3'
services:
  dillinger:
    build: .
    container_name: dillinger
    image: joemccann/dillinger
    ports:
      - "12345:12345"
    environment:
      - "BIND_ADDRESS=0.0.0.0"
      - "PORT=12345"
